[project]
name = "project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipynbname>=2025.8.0.0",
    "mcp>=1.13.1",
    "requests>=2.32.5",
]
